-- local dap, dapui = require("dap"), require("dapui")
-- 
-- -- Configure dap-ui
-- dapui.setup()
-- 
-- -- Automatically open/close dap-ui when debugging starts/stops
-- dap.listeners.after.event_initialized["dapui_config"] = function()
--   dapui.open()
-- end
-- dap.listeners.before.event_terminated["dapui_config"] = function()
--   dapui.close()
-- end
-- dap.listeners.before.event_exited["dapui_config"] = function()
--   dapui.close()
-- end
-- 
